#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Add Node.js binaries to PATH (especially for macOS or VS Code GUI commits)
export PATH="/usr/local/bin:/opt/homebrew/bin:$/Users/jaskirat/.nvm/versions/node/v23.11.0/bin/node"

npx lint-staged
echo "✅ Pre-commit hook executed!"
